"use client";
import {useMemo,useState} from "react";
const ideas=[
 {name:"AI Study Companion",tag:"AI",score:86,status:"Research",desc:"Turns course material into adaptive revision plans and practice sessions."},
 {name:"Life Admin Hub",tag:"Utility",score:82,status:"Concept",desc:"One calm workspace for bills, reminders, documents and recurring life tasks."},
 {name:"AppPulse",tag:"Research",score:79,status:"Discovery",desc:"A lightweight market-intelligence workspace for analysing apps, reviews and competitors."}
];
export default function Home(){const [selected,setSelected]=useState(0);const [query,setQuery]=useState("");const filtered=useMemo(()=>ideas.filter(x=>(x.name+x.desc).toLowerCase().includes(query.toLowerCase())),[query]);return <main>
<header><div className="brand"><span className="mark">G</span><div><strong>GNU</strong><small>PRODUCT LAB</small></div></div><div className="top"><span className="live"><i/> Operating</span><button>+ New idea</button></div></header>
<section className="hero"><div><p className="eyebrow">PRODUCT FACTORY · 001</p><h1>From idea to <em>shipped.</em></h1><p className="lead">One command centre for research, product, design, engineering and launch.</p></div><div className="metric"><span>ACTIVE PIPELINE</span><b>03</b><small>ideas under evaluation</small></div></section>
<section className="grid"><aside><div className="sectionHead"><span>Pipeline</span><b>03</b></div><input placeholder="Search ideas..." value={query} onChange={e=>setQuery(e.target.value)}/><div className="cards">{filtered.map((x,i)=><button className={i===selected?"card active":"card"} onClick={()=>setSelected(i)} key={x.name}><div className="row"><span className="tag">{x.tag}</span><span className="score">{x.score}</span></div><h3>{x.name}</h3><p>{x.desc}</p><div className="status">{x.status}<span>→</span></div></button>)}</div></aside>
<div className="workspace"><div className="workspaceTop"><div><p className="eyebrow">SELECTED OPPORTUNITY</p><h2>{ideas[selected].name}</h2></div><span className="pill">{ideas[selected].status}</span></div><div className="scoreBox"><div><small>OPPORTUNITY SCORE</small><strong>{ideas[selected].score}<sup>/100</sup></strong></div><div className="bar"><span style={{width:ideas[selected].score+"%"}}/></div></div><div className="phases"><div className="phase done"><span>01</span><div><b>Research</b><small>Market · users · competition</small></div><i>✓</i></div><div className="phase current"><span>02</span><div><b>Product</b><small>Problem · MVP · PRD</small></div><i>→</i></div><div className="phase"><span>03</span><div><b>Build</b><small>Design · code · QA</small></div><i>○</i></div><div className="phase"><span>04</span><div><b>Launch</b><small>Deploy · measure · iterate</small></div><i>○</i></div></div><div className="next"><div><small>NEXT ACTION</small><h3>Validate the problem before writing code.</h3><p>Research demand, competing solutions and recurring user complaints. The research wing owns the evidence; product converts it into a build decision.</p></div><button>Open research brief →</button></div></div></section>
<footer><span>GNU / LAUNCHPAD v0.1</span><span>Research → Product → Design → Engineering → Launch</span></footer>
</main>}